# Generated by Django 2.0.1 on 2018-01-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Gender',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
